#!/bin/bash -l
##[RUN] WALLTIME	20:00:00
##[RUN] MEMORY	30gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	fastqc
##[RUN] ACCOUNT	default_project
##[VERSION] pikaDEV 
##[HELP] This tool will create a qc report of the fastq files
##[HELP] This script is multithreaded
##[HELP] This script runs between 1 and 10 minutes per fastq file
##
##[HOWTO] #FASTQC
##[HOWTO] #start the module:
##[HOWTO] pikasub fastqc.pbs
#loading the modules
#extra_modules
module load FastQC

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/fastq";
SCRATCH_DIR=~;
OUTPUT_DIR="$PROJECT_DIR/fastqc";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync $SAMPLE_DIR/*fastq.gz .;

mkdir -p $OUTPUT_DIR;
for i in `ls -1 -d *.fastq.gz`;
do
	files="$files $i";
done

fastqc -o $OUTPUT_DIR -t 20 -d $TMP_DIR $files;

rm -rf $TMP_DIR;
