#!/bin/bash -l
##[RUN] WALLTIME	20:00:00
##[RUN] MEMORY	30gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	regzip
##[RUN] ACCOUNT	default_project
##[VERSION] pikaDEV 
##[HELP] This tool will unzip files, and zip them again (can be usefull if gzip files are from older systems)
##[HELP] This script will use only one cpu
##
##[HOWTO] #reGZIP
##[HOWTO] #start the module:
##[HOWTO] pikasub regzip.pbs
#loading the modules
#extra_modules

#setting all parameters (these could be changed)
PROJECT_DIR="";
RUN_DIR="$PROJECT_DIR/raw";

#the actual script
cd $RUN_DIR/$RUN;
for i in `ls -1 -d *gz`;
do
	j=`echo $i | sed 's/.gz//g'`;
	gunzip $i;
	gzip $j;
done


