#!/bin/bash -l
##[RUN] WALLTIME	12:00:00
##[RUN] MEMORY	20gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	1
##[RUN] NAME	bowtie_index
##[RUN] ACCOUNT	default_project
##[VERSION] pikaDEV
##[HELP] This tool will create the needed indexes for bowtie mapping
##[HELP] This script will use only one cpu
##[HELP] This script has a long runtime (multiple houres)
##
##[HOWTO] #Bowtie index
##[HOWTO] #the genome directory in this script has to be changed
##[HOWTO] #the fasta file needs to be named genome.fa
##[HOWTO] #start the module:
##[HOWTO] pikasub bowtie_index.pbs
#loading the modules
#extra_modules
module load Bowtie2
version_Bowtie2="Bowtie2"

#setting all parameters (these could be changed)
PROJECT_DIR="";
GENOME_DIR="$PROJECT_DIR";

#the actual script

#creating index
cd $GENOME_DIR;
mkdir -p $version_Bowtie2;
cd $version_Bowtie2;
rsync -ahrL $GENOME_DIR/genome.fa .;
bowtie2-build $GENOME_DIR/$version_Bowtie2/genome.fa $GENOME_DIR/$version_Bowtie2/genome;
cd ..;
chmod 555 -R $version_Bowtie2;

