#!/bin/bash -l
##[RUN] WALLTIME	6:00:00:00
##[RUN] MEMORY	240gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	10
##[RUN] NAME	canu_correct
##[RUN] ACCOUNT	default_project
##[RUN] PARTITION	smp1
##[VERSION] pika 16.08 
##[HELP] This tool will correct pacbio data using canu
##[HELP] This script is multithreaded
##[HELP] Runtime of this script is not predicted yet
##
##[HOWTO] #CANU
##[HOWTO] #The parameters in this script has to be edited before ran
##[HOWTO] #start the module:
##[HOWTO] qsub canu_correct.pbs
#loading the modules
#extra_modules
module load canu

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/raw";
OUTPUT_DIR="$PROJECT_DIR/canu";
SAMPLE="";
#this needs to be changed: example 1.1g 4.3m ...
GENOME_SIZE="1.1g";
SCRATCH_DIR=~;
SCRATCH_DIR="$SCRATCH_DIR/canu_$SAMPLE";
MAX_MEM="240";
MAX_THREADS="10";
#uncommand for low coverage settings:
#best is to try different errorRates, examples on the website are 0.035, 0.025, 0.013
EXTRA_SETTINGS="";
#EXTRA_SETTINGS="corMinCoverage=2 errorRate=0.035 minOverlapLength=499 corMaxEvidenceErate=0.3";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/$SAMPLE.fastq.gz pacbio.fastq.gz;

#running CANU
canu -correct -p $SAMPLE -d $TMP_DIR genomeSize=$GENOME_SIZE usegrid=0 maxMemory=$MAX_MEM maxThreads=$MAX_THREADS $EXTRA_SETTINGS -pacbio-raw $TMP_DIR/pacbio.fastq.gz;

mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* .;

rm -r $TMP_DIR;
