#!/bin/bash -l
##[RUN] WALLTIME	6:00:00:00
##[RUN] MEMORY	240gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	10
##[RUN] NAME	links
##[RUN] ACCOUNT	default_project
##[RUN] PARTITION	smp1
##[VERSION] pika 16.08 
##[HELP] This tool will do a scaffolding of illumina data, using pacbio long reads
##[HELP] Runtime of this script is not predicted yet
##
##[HOWTO] #LINKS
##[HOWTO] #The parameters in this script has to be edited before ran
##[HOWTO] #start the module:
##[HOWTO] module load cerebro
##[HOWTO] qsub links.pbs
#loading the modules
#extra_modules
module load LINKS

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/raw";
CONTIG_FILE="$PROJECT_DIR/contigs.fa";
OUTPUT_DIR="$PROJECT_DIR/links";
SAMPLE="links";
SCRATCH_DIR=~;

##add all uncommented and changed variables into this one:
EXTRA_SETTINGS="-b $SAMPLE";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

mkdir raw;
cd raw;
rsync -ahrL $SAMPLE_DIR/* .;
gunzip *gz;
cd ..;
rsync -ahrL $CONTIG_FILE genome.fa;

for i in `ls -1 -d $TMP_DIR/raw/*`;
do
	echo $i >> pacbio_fastq_list.txt;
done

LINKS -f genome.fa -s pacbio_fastq_list.txt;

rm -r $TMP_DIR/raw;
rm -r genome.fa;
mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* .;

rm -r $TMP_DIR;
