#!/bin/bash -l
##[RUN] WALLTIME	3:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	sga_fmmerge
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This tool merges sga filtered data on overlaps, and removes duplicates
##[HELP] This script can be ran multithreaded (use the THREADS parameter)
##[HELP] Runtime depends on the kmer and library size
##
##[HOWTO] #SGA fmmerge
##[HOWTO] #executes fmmerge and rmdup
##[HOWTO] #start the module:
##[HOWTO] qsub sga_fmmerge.pbs
#extra_modules
module load SGA

PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/sga_filter";
OUTPUT_DIR="$PROJECT_DIR/sga_fmmerge";
SCRATCH_DIR="$PROJECT_DIR/tmp/sga_fmmerge_output";
THREADS="20";
#parameters discribed in the example:
FMERGE_OPTIONS="-m 65";
#FMERGE_OPTIONS:"-m 65"; #which is the minimum overlap to merge

#the script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/* .;
gunzip *;

sga fm-merge $FMERGE_OPTIONS -t $THREADS final.filter.pass.fa;
rm final.filter.pass.fa;
sga rmdup -t $THREADS final.filter.pass.merged.fa;
rm final.filter.pass.merged.fa;
sga index -d 2000000 -t $THREADS final.filter.pass.merged.rmdup.fa;

gzip *fa;
mkdir -p $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
