#!/bin/bash -l
##[RUN] WALLTIME	2:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	2
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	sga_correct
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This is a worker script: it uses SAMPLE and THREADS parameters
##[HELP] This tool do the sga correcting
##[HELP] This script can be ran multithreaded (use the THREADS parameter)
##[HELP] Runtime depends on the kmer and library size
##
##[HOWTO] #SGA correct
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE and a THREADS column
##[HOWTO] #This uses worker
##[HOWTO] module load worker
##[HOWTO] #start the module:
##[HOWTO] #for only using 1 thread per sample:
##[HOWTO] wsub -batch sga_correct.pbs -data samples.txt
##[HOWTO] #for using multiple threads (this case 20)
##[HOWTO] wsub -batch sga_correct.pbs -data samples.txt -threaded 20
#extra_modules
module load SGA

#parameters
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/sga_preprocess";
OUTPUT_DIR="$PROJECT_DIR/sga_correct";
SCRATCH_DIR="$PROJECT_DIR/tmp/sga_correct_output";
KMER=41;

#script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/$SAMPLE* .;
gunzip *gz;

sga correct -t $THREADS -k $KMER --discard --learn final.fastq -o error_corrected.fastq;

rm $SAMPLE*;
mv error_corrected.fastq $SAMPLE.ec.k$KMER.fastq;

sga index -d 5000000 -t $THREADS $SAMPLE.ec.k$KMER.fastq;

mkdir -p $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR/$SAMPLE;
