#!/bin/bash -l
##[RUN] WALLTIME	2:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	stride_assemble
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This tool do the stride assemble
##[HELP] Runtime depends on the indexing step
##
##[HOWTO] #StriDe assemble
##[HOWTO] #start the module:
##[HOWTO] qsub stride_assemble.pbs
#loading the modules
#extra_modules
module load Stride

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/stride_overlap";
OUTPUT_DIR="$PROJECT_DIR/stride_assemble";
SCRATCH_DIR="$PROJECT_DIR/tmp";
THREADS="20";
ASSEMBLE_OPTIONS="-k 31 -p output -r 100 -i 200";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/* .;

stride assemble $ASSEMBLE_OPTIONS -t $THREADS merged.filter.pass.asqg.gz;

mkdir -p $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
