#!/bin/bash -l
##[RUN] WALLTIME	2:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	stride_fmwalk
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This tool do the stride fmwalk
##[HELP] Runtime depends on the indexing step
##
##[HOWTO] #StriDe fmwalk
##[HOWTO] #start the module:
##[HOWTO] qsub stride_fmwalk.pbs
#loading the modules
#extra_modules
module load Stride
#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/stride_correct";
OUTPUT_DIR="$PROJECT_DIR/stride_fmwalk";
SCRATCH_DIR="$PROJECT_DIR/tmp";
THREADS="20";
FMWALK_OPTIONS="-m 80 -M 95 -L 32 -I 400 -k 31";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/* .;
gunzip *gz;

stride fmwalk $FMWALK_OPTIONS -t $THREADS -p corrected corrected.fa;
cat corrected.merge.fa corrected.kmerized.fa > merged.fa;

rm corrected.*;
stride index -t $THREADS merged.fa;
gzip merged.fa;
mkdir -p $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
