#!/bin/bash -l
##[RUN] WALLTIME	2:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	stride_overlap
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This tool do the stride overlap
##[HELP] Runtime depends on the indexing step
##
##[HOWTO] #StriDe overlap
##[HOWTO] #start the module:
##[HOWTO] qsub stride_overlap.pbs
#loading the modules
#extra_modules
module load Stride
#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/stride_filter";
OUTPUT_DIR="$PROJECT_DIR/stride_overlap";
SCRATCH_DIR="$PROJECT_DIR/tmp";
THREADS="20";
OVERLAP_OPTIONS="-m 30";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/merged.filter.pass* .;
gunzip *gz;

stride overlap $OVERLAP_OPTIONS -t $THREADS merged.filter.pass.fa;

rm merged.filter.pass.fa;
mkdir -p $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
