#!/bin/bash -l
##[RUN] WALLTIME	2:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	stride_correct
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This tool do the stride correcting
##[HELP] Runtime depends on the indexing step
##
##[HOWTO] #StriDe correcting
##[HOWTO] #start the module:
##[HOWTO] qsub stride_correct.pbs
#loading the modules
#extra_modules
module load Stride

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/stride_preprocess";
OUTPUT_DIR="$PROJECT_DIR/stride_correct";
SCRATCH_DIR="$PROJECT_DIR/tmp";
THREADS="20";
CORRECT_OPTIONS="-a ropebwt2 -k 31 -x 3";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/* .;
gunzip *gz;

stride correct $CORRECT_OPTIONS -t $THREADS reads.fa -o corrected.fa;
stride index -t $THREADS corrected.fa;

rm reads*;
gzip corrected.fa;
mkdir -p $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/corrected* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
