#!/bin/bash -l
##[RUN] WALLTIME	2:00:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	stride_preprocess
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08 
##[HELP] This tool do the stride preprocessing
##[HELP] Runtime depends on the indexing step
##
##[HOWTO] #StriDe preprocess
##[HOWTO] #start the module:
##[HOWTO] qsub stride_preprocess.pbs
#loading the modules
#extra_modules
module load Stride

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/trimmomatic";
OUTPUT_DIR="$PROJECT_DIR/stride_preprocess";
SCRATCH_DIR="$PROJECT_DIR/tmp";
THREADS="20";
PREPROCESS_OPTIONS="--discard-quality";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

mkdir raw;
cd raw;
rsync -ahrL $SAMPLE_DIR/*.R?.fastq.gz .;
gunzip *gz;
cd ..;

FASTQ_FILES="";
PAIRED="-p 1";
for i in `ls $TMP_DIR/raw/*R1* | grep -v "unpaired"`; do
	j=`echo $i | sed 's:R1:R2:g'`;
	if [ -f $j ];
	then 
		#paired end
		#PAIRED="-p 1";
        	FASTQ_FILES="$FASTQ_FILES $i $j";
	else
        	#single read
		PAIRED="-p 0";
        	FASTQ_FILES="$FASTQ_FILES $i";
	fi
done

stride preprocess $PREPROCESS_OPTIONS $PAIRED $FASTQ_FILES -o reads.fa;
rm -r $TMP_DIR/raw;
stride index -a ropebwt2 -t $THREADS reads.fa;

gzip reads.fa;
mkdir -p $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
