#!/bin/bash -l
##[RUN] WALLTIME	12:00:00
##[RUN] MEMORY	20gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	1
##[RUN] NAME	bwa_index
##[RUN] ACCOUNT	default_project
##[VERSION] pika 1701
##[HELP] This tool will create the bwa index for the genome
##[HELP] This script will use only one cpu
##[HELP] This script has a longer runtime (couple of houres)
##
##[HOWTO] #BWA index
##[HOWTO] #the genome directory in the script has to be changed
##[HOWTO] #the fasta file has to be named genome.fa
##[HOWTO] #start the module:
##[HOWTO] wsub -batch bamtobed.pbs -data samples.txt
#loading the modules
#extra_modules
module load BWA
version_BWA="BWA"

PROJECT_DIR="";
GENOME_DIR="$PROJECT_DIR";

#creating index

cd $GENOME_DIR;
mkdir -p $version_BWA;
cd $version_BWA;
rsync -ahrL $GENOME_DIR/genome.fa .;
bwa index $GENOME_DIR/$version_BWA/genome.fa;
cd ..
chmod 555 -R $version_BWA;

