#!/bin/bash -l
##[RUN] WALLTIME	12:00:00
##[RUN] MEMORY	50gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	htseq
##[RUN] ACCOUNT	default_project
##[VERSION] pika 1701 
##[HELP] This is a worker script: it uses SAMPLE parameters
##[HELP] This script will generate a counts file, with the counts of given features
##[HELP] This script will use only one cpu
##[HELP] This script runs only a 1 minute per 1M reads
##
##[HOWTO] #HTSEQ-count
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE column
##[HOWTO] #This uses worker
##[HOWTO] module load worker
##[HOWTO] #start the module:
##[HOWTO] wsub -batch htseq.pbs -data samples.txt
##
##[HELP] Options:
##[HELP] genome: the genome to use (abriviation if known or full path)
##[OPTIONS] genome	mandatory	sed "s:GENOME_DIR=\"\":GENOME_DIR=\"value\":g"
##[HELP] ensembl: version of the ensembl to use (standard current link)
##[OPTIONS] ensembl	mandatory	sed "s:ENSEMBL=\"current\":ENSEMBL=\"value\":g"
##[HELP] strict: yes for the strict counting, no for flexible counting
##[OPTIONS] strict	optional	sed "s:STRICT=\"yes\":STRICT=\"value\":g"

#loading the modules
#extra_modules
module load SAMtools;
module load HTSeq;

#setting all parameters (these could be changed)
PROJECT_DIR="";
GENOME_DIR="";
ENSEMBL="current";
SAMPLE_DIR="$PROJECT_DIR/mapped";
OUTPUT_DIR="$PROJECT_DIR/htseq";
SCRATCH_DIR=~;
GENES_ANNOTATION_FILE="$GENOME_DIR/Ensembl/$ENSEMBL/genes.gtf";
#strict (yes), flexible (no)
STRICT="yes";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

if [ "$STRICT" == "yes" ];
then
	HTSEQ_PARAM="-s yes -a 10 -i gene_name -t gene -m union";
	OUTPUT_FILE_NAME="$SAMPLE.htseq_a10_genes_strand_union.counts";
else
	HTSEQ_PARAM="-s no -a 0 -i gene_name -t gene -m intersection-nonempty";
	OUTPUT_FILE_NAME="$SAMPLE.htseq_a0_genes_nostrand_intersectionNonempty.counts";
fi

cd $TMP_DIR;
rsync -ahr $SAMPLE_DIR/$SAMPLE.bam .;

#BAM to SAM
samtools view $SAMPLE.bam > $SAMPLE.sam;
#COUNT REGIONS
htseq-count $HTSEQ_PARAM $SAMPLE.sam $GENES_ANNOTATION_FILE > $OUTPUT_FILE_NAME

mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/$OUTPUT_FILE_NAME .;

rm -r $TMP_DIR;


