#!/bin/bash -l
##[RUN] WALLTIME	12:00:00
##[RUN] MEMORY	100gb
##[RUN] NODES	10
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	star_mapping_population
##[RUN] ACCOUNT	default_project
#This is a worker script: it uses the SAMPLE parameters
##[VERSION] pikaDEV
##[HELP] This is a worker script: it uses SAMPLE parameters
##[HELP] This tool will map the reads to the reference genome
##[HELP] This script will use only one cpu per sample
##[HELP] This script runs only 2 minutes per 1M reads
##[HELP] This scripts needs to be edited: change the flash parameter, and the genome directory in the prolog file
##
##[HOWTO] #STAR mapping for populations
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE column
##[HOWTO] #This uses worker
##[HOWTO] module load worker
##[HOWTO] #The script need to be edited: change the flash parameter
##[HOWTO] #The genome directory in the prolog file will need to be changed
##[HOWTO] #When the THREADS variable in this script is changed, this can be ran as multithreaded population mapping, start like this (replace 20 with the number of given threads) (standard multithreaded):
##[HOWTO] wsub -batch star_mapping_population.pbs -data samples.txt -prolog star_mapping_population.prolog.sh -threaded 20
##
##[HELP] Options:
##[HELP] genome: the genome to use (abriviation if known or full path)
##[OPTIONS] genome	mandatory	sed 's:GENOME_DIR=\"\":GENOME_DIR=\"value\":g'

#loading the modules
#extra_modules
module load STAR
module load elprep
module load SAMtools
version_STAR="STAR"

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/bbduk";
OUTPUT_DIR="$PROJECT_DIR/mapped";
SCRATCH_DIR=~;
GENOME_DIR="";
#This parameter can be changed for multithreaded mapping
THREADS="20";

#batchline

#the actual script
JOBID="";
GENOME_DIR="$GENOME_DIR/$version_STAR"

mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $SAMPLE_DIR/$SAMPLE*.fastq.gz $TMP_DIR/;
gunzip *gz;
FASTQ_FILES="";

STAR --runMode alignReads --runThreadN $THREADS --genomeDir $GENOME_DIR --readFilesIn $SAMPLE.R1.fastq --outStd SAM --outSAMtype SAM --outFileNamePrefix $TMP_DIR/$SAMPLE | elprep /dev/stdin $SAMPLE".bam" --replace-read-group "ID:$SAMPLE LB:$SAMPLE PL:illumina SM:$SAMPLE CN:GenomicsCoreLeuven" --sorting-order coordinate --nr-of-threads $THREADS;
rm *fastq;

samtools index -b $TMP_DIR/$SAMPLE.bam;

mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/$SAMPLE* .;
rm -rf $TMP_DIR;



