#!/bin/bash -l
##[RUN] WALLTIME	6:00:00
##[RUN] MEMORY	30gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	fastq_join
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08
##[HELP] This is a worker script: it uses SAMPLE parameters
##[HELP] This tool will join fastq files (e.g. same samples, but different runs/lanes)
##[HELP] This script will use only one cpu per samples
##[HELP] This script is a cat and gzip of files, so runtime is limited
##
##[HOWTO] #FASTQ_JOIN
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE column
##[HOWTO] #This uses worker
##[HOWTO] module load worker
##[HOWTO] #start the module:
##[HOWTO] wsub -batch fastq_join.pbs -data samples.txt
#loading the modules
#extra_modules


#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/raw";
OUTPUT_DIR="$PROJECT_DIR/fastq_join";
SCRATCH_DIR=~;

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;


R1count=`ls -1 -d $SAMPLE_DIR/*/$SAMPLE.R1.fastq.gz | wc -l`;
R2count=`ls -1 -d $SAMPLE_DIR/*/$SAMPLE.R2.fastq.gz | wc -l`;

#check if only R1s, or counts are same, else exit
if [ "$R1count" -eq "$R2count" ] || [ "$R2count" -eq "0" ]; 
then 
	#equal number, or no R2 files
	for i in `ls -1 -d $SAMPLE_DIR/*/$SAMPLE.R1.fastq.gz`;
	do
		zcat $i >> $TMP_DIR/$SAMPLE.R1.fastq;
		if [ "$R2count" -ne "0" ];
	        then
        	        #R2 files exists
			j=`echo $i | sed 's/R1/R2/'`;
			zcat $j >> $TMP_DIR/$SAMPLE.R2.fastq; 
       		fi
	done
else
	#different number, so error exit
	rm -r $TMP_DIR;
	exit 1;
fi

gzip $SAMPLE*;
mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/$SAMPLE.R?.fastq.gz .;

rm -r $TMP_DIR;


