#!/bin/bash -l
#PBS -l walltime=6:00:00
#PBS -l mem=30gb
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -M MAIL
#PBS -m eab
#PBS -N flash
#PBS -A default_project
##[VERSION] pika 16.08
##[HELP] This is a worker script: it uses SAMPLE parameters
##[HELP] This tool will merge overlapping reads to 1 (ends with 3 files: R1, R2 of non overlapping, and overlapped reads)
##[HELP] This script will use only one cpu per sample
##[HELP] This scripts runtime is limited (less then some houres) 
##
##[HOWTO] #FLASH
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE column
##[HOWTO] #This uses the 2015a (there can be a more recent worker installed)
##[HOWTO] source switch_to_2015a
##[HOWTO] module load worker/1.6.4-intel-2015a
##[HOWTO] #start the module:
##[HOWTO] wsub -batch flash.pbs -data samples.txt

##[HELP] Options:
##[HELP] use_trimmomatic: yes if the result needed to use is a trimmomatic result
##[OPTIONS] use_trimmomatic	optional	sed 's:IS_TRIMMOMATIC=\"no\":IS_TRIMMOMATIC=\"value\":g'

#loading the modules
module load FLASH/1.2.10

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/raw";
OUTPUT_DIR="$PROJECT_DIR/flash";
SCRATCH_DIR=$VSC_SCRATCH_NODE;
IS_TRIMMOMATIC="no";

#the actual script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahr $SAMPLE_DIR/$SAMPLE* .;

flash -z -d $TMP_DIR -o $SAMPLE $TMP_DIR/$SAMPLE.R1.fastq.gz $TMP_DIR/$SAMPLE.R2.fastq.gz > $TMP_DIR/$SAMPLE.flash.log 2> $TMP_DIR/$SAMPLE.flash.log;

if [ "$IS_TRIMMOMATIC" == "yes" ];
then
	zcat $SAMPLE.extendedFrags.fastq.gz > $SAMPLE.tmp.fastq;
	zcat $SAMPLE.unpaired.forward.fastq.gz >> $SAMPLE.tmp.fastq;
	zcat $SAMPLE.unpaired.reverse.fastq.gz >> $SAMPLE.tmp.fastq;
	rm $SAMPLE.extendedFrags.fastq.gz;
	mv $SAMPLE.tmp.fastq $SAMPLE.extendedFrags.fastq;
	gzip $SAMPLE.extendedFrags.fastq;
	rm $SAMPLE.unpaired*;
fi

rm $SAMPLE.R?.fastq.gz;

mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* .;

rm -rf $TMP_DIR;


