#!/bin/bash -l
#PBS -l walltime=20:00:00
#PBS -l mem=30gb
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -M MAIL 
#PBS -m eab
#PBS -N regzip
#PBS -A default_project
##[VERSION] pika 16.08 
##[HELP] This tool will unzip files, and zip them again (can be usefull if gzip files are from older systems)
##[HELP] This script will use only one cpu
##
##[HOWTO] #reGZIP
##[HOWTO] #start the module:
##[HOWTO] qsub regzip.pbs
#loading the modules

#setting all parameters (these could be changed)
PROJECT_DIR="";
RUN_DIR="$PROJECT_DIR/raw";

#the actual script
cd $RUN_DIR/$RUN;
for i in `ls -1 -d *gz`;
do
	j=`echo $i | sed 's/.gz//g'`;
	gunzip $i;
	gzip $j;
done


