#!/bin/bash -l
##[RUN] WALLTIME	10:00:00
##[RUN] MEMORY	120gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	gbsy
##[RUN] ACCOUNT	default_project
##[VERSION] pika 1701
##[HELP] This tool is a test tool to select the correct locations for variant calling 
##
##[HOWTO] #GBSY
##[HOWTO] #start the module:
##[HOWTO] qsub gbsy.pbs 
#loading the modules
#extra_modules
module load gbsy/v0.0alpha-Java1.8.0_77

#setting all parameters (these could be changed)
PROJECT_DIR="";
INPUT_DIR="$PROJECT_DIR/bamtobed_corrected";
OUTPUT_DIR="$PROJECT_DIR/gbsy";
SCRATCH_DIR=~;
THREADS="1";
GBSY_OPTIONS="-msp 0.5 -mo 5";

#the actual script
#do the copy and demultiplexing
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahrL $INPUT_DIR/* .;

gunzip *;

BED_LIST="";
for i in `ls -1 -d *bed`;
do
	BED_LIST="$BED_LIST -b $i";
done

GBSY uniter $BED_LIST $GBSY_OPTIONS -prefix gbsy;

mkdir -p $OUTPUT_DIR/$RUN;
cd $OUTPUT_DIR/$RUN;
rsync -ahrL $TMP_DIR/gbsy* .;

rm -rf $TMP_DIR;


