#!/bin/bash -l
#PBS -l walltime=20:00:00:00
#PBS -l mem=240gb
#PBS -l nodes=1:ppn=10
#PBS -M MAIL
#PBS -N abyss
#PBS -A default_project
#PBS -l partition=smp1
##[VERSION] pika 16.08 
##[HELP] This is a regular script
##[HELP] This tool will assemble illumina data
##[HELP] This script is multithreaded. 
##[HELP] This script runs for around 3 days, using 60 cpus (cerebro) for 2 rapid lanes hiseq2500
##[HELP] This script needs to be edited before run
##
##[HOWTO] #ABYSS
##[HOWTO] #The script needs to be edited before ran (edit the information about the se and pe libraries, as well as inserting the correct file names)
##[HOWTO] #start the module:
##[HOWTO] qsub abyss.pbs
#loading the modules
#extra_modules
module use /apps/leuven/thinking/2015a/modules/all 
module load ABySS/1.9.0-intel-2015a-Python-2.7.9
#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/";
KMER="31";
SAMPLE="sample";
OUTPUT_DIR="$PROJECT_DIR/abyss_$KMER";
SCRATCH_DIR=~;

#the actual script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync $SAMPLE_DIR/$SAMPLE*.gz .;
gunzip *gz;

#normal run
#paired end data should start with pe, all pe libraries should be listed in the lib variable
## lib="pe1 pe2" pe1="run1.R1.fastq run1.R2.fastq" pe2="run2.R1.fastq run2.R2.fastq"
#single end data can be added with the se variable, all se can be added after each other
## se="run1.R1.fastq run2.R1.fastq"
NAME=$SAMPLE"_k"$KMER;
abyss-pe name="$NAME" k=$KMER lib="pe250_1 pe250_2" pe250_1="GC029509.160212_microflor_denovo.160222.HiSeq2500.FCA.lane1.gcap_dev.R1.fastq GC029509.160212_microflor_denovo.160222.HiSeq2500.FCA.lane1.gcap_dev.R2.fastq" pe250_2="GC029509.160212_microflor_denovo.160222.HiSeq2500.FCA.lane2.gcap_dev.R1.fastq GC029509.160212_microflor_denovo.160222.HiSeq2500.FCA.lane2.gcap_dev.R2.fastq" np=10 j=10;

rm *fastq;
mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahrL $TMP_DIR .;
rm -r $TMP_DIR;
