#!/bin/bash -l
#PBS -l walltime=6:00:00:00
#PBS -l mem=240gb
#PBS -l nodes=1:ppn=10
#PBS -M MAIL
#PBS -m eab
#PBS -N canu
#PBS -A default_project
#PBS -l partition=smp1
##[VERSION] pika 16.08 
##[HELP] This tool will assemble pacbio data
##[HELP] This script is multithreaded
##[HELP] Runtime of this script is not predicted yet
##
##[HOWTO] #CANU
##[HOWTO] #The parameters in this script has to be edited before ran
##[HOWTO] #start the module:
##[HOWTO] qsub canu.pbs
#loading the modules
module use /apps/leuven/thinking/2015a/modules/all 
module load canu/1.0-GCC-4.9.2

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/raw";
OUTPUT_DIR="$PROJECT_DIR/canu";
SAMPLE="";
GENOME_SIZE="1.1g";
SCRATCH_DIR="$VSC_SCRATCH_NODE";
MAX_MEM="240";
MAX_THREADS="10";
#uncommand for low coverage settings:
EXTRA_SETTINGS="";
#EXTRA_SETTINGS="corMinCoverage=2 errorRate=0.035 minOverlapLength=499 corMaxEvidenceErate=0.3";

#the actual script
mkdir -p $SCRATCH_DIR/canu_output;
cd $SCRATCH_DIR/canu_output;
rsync -ahrL $SAMPLE_DIR/$SAMPLE.fastq.gz pacbio.fastq.gz;

#running CANU
canu -p $SAMPLE -d $SCRATCH_DIR/canu_output genomeSize=$GENOME_SIZE usegrid=0 maxMemory=$MAX_MEM maxThreads=$MAX_THREADS $EXTRA_SETTINGS -pacbio-raw $SCRATCH_DIR/canu_output/pacbio.fastq.gz;

mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahrL $SCRATCH_DIR/canu_output/* .;

