#!/bin/bash -l
#PBS -l walltime=3:00:00:00
#PBS -l mem=120gb
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -M MAIL
#PBS -m eab
#PBS -N sga_fmmerge
#PBS -A default_project
##[VERSION] pika 16.08 
##[HELP] This tool merges sga filtered data on overlaps, and removes duplicates
##[HELP] This script can be ran multithreaded (use the THREADS parameter)
##[HELP] Runtime depends on the kmer and library size
##
##[HOWTO] #SGA fmmerge
##[HOWTO] #executes fmmerge and rmdup
##[HOWTO] #start the module:
##[HOWTO] qsub sga_fmmerge.pbs
#extra_modules
module use /apps/leuven/thinking/2015a/modules/all 
module load SGA/0.10.14-foss-2015a

PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/sga_filter";
OUTPUT_DIR="$PROJECT_DIR/sga_fmmerge";
SCRATCH_DIR="$PROJECT_DIR/tmp/sga_fmmerge_output";
THREADS="20";
#parameters discribed in the example:
FMERGE_OPTIONS="-m 65";
#FMERGE_OPTIONS:"-m 65"; #which is the minimum overlap to merge

#the script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync -ahrL $SAMPLE_DIR/* .;
gunzip *;

sga fm-merge $FMERGE_OPTIONS -t $THREADS final.filter.pass.fa;
rm final.filter.pass.fa;
sga rmdup -t $THREADS final.filter.pass.merged.fa;
rm final.filter.pass.merged.fa;
sga index -d 2000000 -t $THREADS final.filter.pass.merged.rmdup.fa;

gzip *fa;
mkdir -p $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
