#!/bin/bash -l
#PBS -l walltime=3:00:00:00
#PBS -l mem=120gb
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -M MAIL
#PBS -m eab
#PBS -N sga_filter
#PBS -A default_project
##[VERSION] pika 16.08 
##[HELP] This tool filters sga corrected data
##[HELP] This script can be ran multithreaded (use the THREADS parameter)
##[HELP] Runtime depends on the kmer and library size
##
##[HOWTO] #SGA filtesr
##[HOWTO] #start the module:
##[HOWTO] qsub sga_filter.pbs
#extra_modules
module load SGA

PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/sga_merge";
OUTPUT_DIR="$PROJECT_DIR/sga_filter";
SCRATCH_DIR="$PROJECT_DIR/tmp/sga_filter_output";
THREADS="20";
#parameters discribed in the example:
FILTER_OPTIONS="";
#FILTER_OPTIONS:"-d 256 -x 2";

#the script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync -ahrL $SAMPLE_DIR/* .;
gunzip *;

sga filter $FILTER_OPTIONS -t $THREADS final.fastq;

rm final.bwt final.fastq final.rbwt final.rsai final.sai;

gzip *fa;
mkdir -p $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
