#!/bin/bash -l
#PBS -l walltime=3:00:00:00
#PBS -l mem=120gb
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -M MAIL
#PBS -m eab
#PBS -N sga_assemble
#PBS -A default_project
##[VERSION] pika 16.08 
##[HELP] This tool does the real contig assembly
##[HELP] This script can be ran multithreaded (use the THREADS parameter)
##
##[HOWTO] #SGA assemble
##[HOWTO] #contig assembly
##[HOWTO] #start the module:
##[HOWTO] qsub sga_assemble.pbs
module use /apps/leuven/thinking/2015a/modules/all 
module load SGA/0.10.14-foss-2015a

PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/sga_overlap";
OUTPUT_DIR="$PROJECT_DIR/sga_assemble";
SCRATCH_DIR="$PROJECT_DIR/tmp/sga_assemble_output";
THREADS="20";
#parameters discribed in the example:
ASSEMBLE_OPTIONS="-m 77 -d 0.4 -g 0.1 -r 10 -l 200";
#-m	min overlap
#-d	remove variation if divergence between seq is less than F
#-g	remove variation if divergence between seq (only count indels) is less than F
#-r	resolve small repeats using spanning overlaps when difference is greater than LEN
#-l	remove terminal branches only if less then LEN

#the script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync -ahrL $SAMPLE_DIR/* .;

sga assemble $ASSEMBLE_OPTIONS final.filter.pass.merged.rmdup.asqg.gz;

rm final.filter.pass.merged.rmdup.asqg.gz;
mkdir -p $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
