#!/bin/bash -l
#PBS -l walltime=3:00:00:00
#PBS -l mem=120gb
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -M MAIL
#PBS -m eab
#PBS -N sga_overlaps
#PBS -A default_project
##[VERSION] pika 16.08 
##[HELP] This tool constructs the string graph of the merged reads
##[HELP] This script can be ran multithreaded (use the THREADS parameter)
##
##[HOWTO] #SGA overlap
##[HOWTO] #constructs the string graph
##[HOWTO] #start the module:
##[HOWTO] qsub sga_overlap.pbs
#extra_modules
module use /apps/leuven/thinking/2015a/modules/all 
module load SGA/0.10.14-foss-2015a

PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/sga_fmmerge";
OUTPUT_DIR="$PROJECT_DIR/sga_overlap";
SCRATCH_DIR="$PROJECT_DIR/tmp/sga_overlap_output";
THREADS="20";
#parameters discribed in the example:
OVERLAP_OPTIONS="-m 65";
#OVERLAP_OPTIONS:"-m 65"; #which is the minimum overlap to merge

#the script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync -ahrL $SAMPLE_DIR/* .;
gunzip *;

sga overlap $OVERLAP_OPTIONS -t $THREADS final.filter.pass.merged.rmdup.fa;
rm final.filter.pass.merged.rmdup.fa;

mkdir -p $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* $OUTPUT_DIR/;
rm -rf $TMP_DIR;
