#!/bin/bash -l
#PBS -l walltime=12:00:00
#PBS -l mem=20gb
#PBS -l nodes=1:ppn=1
#PBS -M MAIL 
#PBS -m eab
#PBS -N bowtie_index
#PBS -A default_project
##[VERSION] pika 16.08
##[HELP] This tool will create the needed indexes for bowtie mapping
##[HELP] This script will use only one cpu
##[HELP] This script has a long runtime (multiple houres)
##
##[HOWTO] #Bowtie index
##[HOWTO] #the genome directory in this script has to be changed
##[HOWTO] #the fasta file needs to be named genome.fa
##[HOWTO] #start the module:
##[HOWTO] qsub bowtie_index.pbs
#loading the modules
#extra_modules
module load Bowtie2

#setting all parameters (these could be changed)
GENOME_DIR="";
BOWTIE_VERSION="2.2.4";

#the actual script

#creating index
cd $GENOME_DIR;
mkdir -p bowtie2/$BOWTIE_VERSION;
cd bowtie2/$BOWTIE_VERSION;
rsync -ahrL $GENOME_DIR/genome.fa .;
bowtie2-build $GENOME_DIR/bowtie2/$BOWTIE_VERSION/genome.fa $GENOME_DIR/bowtie2/$BOWTIE_VERSION/genome;
cd ..;
chmod 555 -R 2.2.4;

