#!/bin/bash -l
##[RUN] WALLTIME	12:00:00
##[RUN] MEMORY	50gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	samtools_mpileup 
##[RUN] ACCOUNT	default_project
##[VERSION] pika dev [here comes the version of pika where the last changes are made, pika dev for the development fase]
##[HELP] This script will run mpileup on all bam files. This is a preparation step for VarScan or other variant calling software.
##[HELP] Output is a mpileup file.
##
##[HOWTO] #Samtools mpileup
##[HOWTO] #This script prepares variant calling using samtools mpileup
##[HOWTO] #The command needed to execute is:
##[HOWTO] qsub samtools_mpileup.pbs
##[HOWTO] #Ideal is to test different parameters for the mpileup.
##
##[HELP] Options:
##[HELP] genome: the genome to use (abriviation if known or full path)
##[OPTIONS] genome	mandatory	sed 's:GENOME_DIR=\"\":GENOME_DIR=\"value\":g'
##[HELP] mpileup_options: the options for mpileup (standard= -B -d 2000 -Q 0)
##[OPTIONS] mpileup_options	optional	sed "s:MPILEUP_OPTIONS=\"-B -d 2000 -Q 0\":MPILEUP_OPTIONS=\"value\":g"

#loading the modules
#extra_modules
module load SAMtools

#setting all parameters (these could be changed)
PROJECT_DIR="";
GENOME_DIR="";
SAMPLE_DIR="$PROJECT_DIR/mapped";
OUTPUT_DIR="$PROJECT_DIR/mpileup";
SCRATCH_DIR=~;
MPILEUP_OPTIONS="-B -d 2000 -Q 0";

#the actual script
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;
rsync -ahrL $SAMPLE_DIR/*ba? .;
for i in `ls -1 -d *.bam`;
do
	echo $i >> bam_list.txt;
done

#creation of the mpileup
samtools mpileup -f $GENOME_DIR/genome.fa -b bam_list.txt $MPILEUP_OPTIONS > result.mpileup;

rm *.ba?;

mkdir -p $OUTPUT_DIR;
rsync -ahrL $TMP_DIR/* $OUTPUT_DIR;
rm -r $TMP_DIR;
