#!/bin/bash -l
##[RUN] WALLTIME	6:00:00
##[RUN] MEMORY	50gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	bamtobed
##[RUN] ACCOUNT	default_project
##[VERSION] pikaDEV
##[HELP] This is a batch script: it uses a sample file
##[HELP] This tool will make a bed file of a bam file
##[HELP] This script will use only one cpu
##[HELP] This script runs only a 1 minute per 1M reads
##
##[HOWTO] #BAMTOBED
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE column (with header)
##[HOWTO] #start the module (if samples.txt is in the job dir):
##[HOWTO] qsub bamtobed.pbs
#loading the modules
#extra_modules
module load BEDTools
module load parallel
#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/mapped";
OUTPUT_DIR="$PROJECT_DIR/bamtobed";
SCRATCH_DIR=~;
NODEFILE="";

if [ -z "$BATCH_FILE" ]; 
then 
	#variable is empty or unset
	SAMPLE_FILE="$PROJECT_DIR/jobs/samples.txt";
else
	SAMPLE_FILE=$BATCH_FILE
fi

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

#setting parallel environment
export PARALLEL="--workdir . --env PATH --env LD_LIBRARY_PATH --env LOADEDMODULES --env _LMFILES_ --env MODULE_VERSION --env MODULEPATH --env MODULEVERSION_STACK --env MODULESHOME --env OMP_DYNAMICS --env OMP_MAX_ACTIVE_LEVELS --env OMP_NESTED --env OMP_NUM_THREADS --env OMP_SCHEDULE --env OMP_STACKSIZE --env OMP_THREAD_LIMIT --env OMP_WAIT_POLICY";
#end setting parallel environment
PARALLEL_JOBS=`nproc`;
cat $NODEFILE | sort | uniq > nodefile

for SAMPLE in `tail -n +2 $SAMPLE_FILE`;
do
        echo "
		cd $TMP_DIR
		mkdir $SAMPLE
		cd $SAMPLE
		rsync -ahr $SAMPLE_DIR/$SAMPLE.bam .
		#check if copy success, else exit
		rc=\$?; if [[ \$rc != 0 ]]; then exit \$rc; fi
		#trimming
		bedtools bamtobed -i $SAMPLE.bam > $SAMPLE.bed
		#check if success, else exit
		rc=\$?; if [[ \$rc != 0 ]]; then exit \$rc; fi
		rm $SAMPLE.bam; gzip $SAMPLE.*
		rsync -ahr $SAMPLE.* $OUTPUT_DIR/
		#check if success, else exit
		rc=\$?; if [[ \$rc != 0 ]]; then exit \$rc; fi
		cd ..; rm -r $SAMPLE
	" >> $TMP_DIR/$SAMPLE.sh;
        echo "$TMP_DIR/$SAMPLE.sh" >> commands.txt
done

cat commands.txt | parallel --sshloginfile nodefile -j "$PARALLEL_JOBS" 'sh {} > {}.log 2> {}.err'

rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi












