#!/bin/bash -l
##[RUN] WALLTIME	6:00:00
##[RUN] MEMORY	50gb
##[RUN] NODES	1
##[RUN] CORES_PER_NODE	20
##[RUN] NAME	bamtobed_gbs
##[RUN] ACCOUNT	default_project
##[VERSION] pika 16.08
##[HELP] This is a worker script: it uses SAMPLE parameters
##[HELP] This tool will make a bed file of a bam file
##[HELP] This script will use only one cpu
##[HELP] This script runs only a 1 minute per 1M reads
##
##[HOWTO] #BAMTOBED gbs correction and filtering
##[HOWTO] #Create a data file (samples.txt), with a SAMPLE column
##[HOWTO] #This uses the worker: 
##[HOWTO] module load worker
##[HOWTO] #start the module:
##[HOWTO] wsub -batch bamtobed_gbs.pbs -data samples.txt
#loading the modules
#extra_modules
module load BEDTools

#setting all parameters (these could be changed)
PROJECT_DIR="";
SAMPLE_DIR="$PROJECT_DIR/mapped_corrected";
OUTPUT_DIR="$PROJECT_DIR/bamtobed_corrected";
SCRATCH_DIR=~;
MINQUAL="6";

#the actual script
JOBID="";
mkdir -p $SCRATCH_DIR/$JOBID;
TMPDIR=$SCRATCH_DIR/$JOBID;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

rsync -ahr $SAMPLE_DIR/$SAMPLE.bam .;

bedtools bamtobed -i $SAMPLE.bam | awk -v minq=$MINQUAL '{if($5>=minq){print $0}}' | sort -k4,4 | awk 'BEGIN{OFS=FS}{if(NR==1){prev=$0;}else{if(prev==""){prev=$0;}else{split(prev,prevarr,FS); split($0,curarr,FS); split(prevarr[4],prevn,"/"); split(curarr[4],curn,"/"); if(prevn[1]==curn[1]){if(prevarr[1]==curarr[1]){if(prevarr[3]==curarr[2]){print curarr[1],prevarr[2],curarr[3],curn[1],((prevarr[5]+curarr[5])/2),"+";}else if(prevarr[2]==curarr[3]){print curarr[1],curarr[2],prevarr[3],curn[1],((prevarr[5]+curarr[5])/2),"-"}else{print prev; print $0;}}else{print prev; print $0;} prev="";}else{print prev; prev=$0;}}}}' | sort -k1,1 -k2,2n -k3,3n > $SAMPLE.bed

rm $SAMPLE.bam;
gzip $SAMPLE*;
mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/$SAMPLE.bed.gz .;

rm -r $TMP_DIR/$SAMPLE;


